import React from "react";
import { ArrowUpRight, CheckCircle2, LockKeyhole } from "lucide-react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { SignalShell, StatusChip } from "@/components/SignalShell";
import { trpc } from "@/lib/trpc";

export default function AdminReviewQueue() {
  const auth = useAuth();
  const isAdmin = auth.user?.role === "admin";
  const queue = trpc.receipts.pendingReview.useQuery({ limit: 50 }, { enabled: isAdmin, retry: false });
  const [notes, setNotes] = React.useState<Record<number, string>>({});
  const review = trpc.receipts.verifyResolutionEvidence.useMutation({ onSuccess: () => queue.refetch() });

  return <SignalShell><div className="pi-workspace">
    <section className="pi-page-intro"><div><div className="pi-kicker"><span>ADMIN</span> Evidence review queue</div><h1>Review the<br /><em>source.</em></h1><p>Only administrators can move submitted evidence into the verified record. Every decision keeps the source URL, integrity commitment, reviewer identity, and review note visible.</p></div><StatusChip tone={isAdmin ? "live" : "unavailable"}>{isAdmin ? "Administrator access" : "Restricted route"}</StatusChip></section>
    {!auth.isAuthenticated ? <section className="pi-panel pi-ledger-empty"><LockKeyhole size={28} /><b>Administrator sign-in required.</b><p>This route never infers reviewer permissions from the browser.</p><button type="button" className="pi-action" onClick={() => startLogin()}>Sign in to continue <ArrowUpRight size={15} /></button></section> : !isAdmin ? <section className="pi-panel pi-ledger-empty"><LockKeyhole size={28} /><b>Review queue restricted.</b><p>Your account is authenticated but does not have administrator review permission.</p></section> : <section className="pi-panel pi-review-queue" data-testid="admin-review-route"><div className="pi-panel-head"><div><div className="pi-kicker"><span>Submitted evidence</span> Awaiting decision</div><h2>{queue.isLoading ? "Loading review queue…" : `${queue.data?.length ?? 0} item${(queue.data?.length ?? 0) === 1 ? "" : "s"} awaiting review`}</h2></div><StatusChip tone={queue.isError ? "unavailable" : "snapshot"}>{queue.isError ? "Error" : "Admin only"}</StatusChip></div>{queue.isError ? <div className="pi-ledger-empty" role="alert"><b>Review queue unavailable.</b><p>No evidence state is inferred while the queue is unavailable.</p><button type="button" className="pi-action" onClick={() => queue.refetch()}>Retry queue</button></div> : queue.data?.length ? <div className="pi-review-list">{queue.data.map(item => <article className="pi-review-entry" key={item.resolution.id} data-testid={`admin-review-${item.resolution.id}`}><div><b>Receipt #{item.receipt.id} · Outcome {item.resolution.outcome}</b><small>{item.resolution.evidenceSummary}</small><a href={item.resolution.sourceUrl} target="_blank" rel="noreferrer">{item.resolution.sourceUrl} <ArrowUpRight size={13} /></a><small>SHA-256 commitment: {item.resolution.evidenceHash}</small><textarea aria-label={`Reviewer notes for receipt ${item.receipt.id}`} placeholder="Reviewer note (optional)" value={notes[item.resolution.id] ?? ""} onChange={event => setNotes({ ...notes, [item.resolution.id]: event.target.value })} /></div><div className="pi-review-actions"><button type="button" className="pi-action" disabled={review.isPending} onClick={() => review.mutate({ resolutionId: item.resolution.id, status: "VERIFIED", reviewerNotes: notes[item.resolution.id] })}>Verify</button><button type="button" className="pi-action pi-action-secondary" disabled={review.isPending} onClick={() => review.mutate({ resolutionId: item.resolution.id, status: "REJECTED", reviewerNotes: notes[item.resolution.id] })}>Reject</button></div></article>)}</div> : <div className="pi-ledger-empty"><CheckCircle2 size={28} /><b>Queue clear.</b><p>New submissions will appear here before affecting verified metrics.</p></div>}{review.error && <p className="pi-error-note" role="alert">{review.error.message}</p>}</section>}
  </div></SignalShell>;
}
