/* Proofcast / Signal Room: Command Center renders only verified DreamDEX snapshots or an explicit unavailable state. */
import { Link } from "wouter";
import { Activity, ArrowRight, Clock3, GitCompareArrows, Layers3, ShieldCheck } from "lucide-react";
import { Metric, ProbabilityBand, SectionHeading, SignalShell, StatusChip } from "@/components/SignalShell";
import { trpc } from "@/lib/trpc";

function remainingLabel(seconds: number) {
  const hours = Math.floor(seconds / 3_600);
  const minutes = Math.floor((seconds % 3_600) / 60);
  return hours > 0 ? `${hours}h ${minutes}m` : `${Math.max(0, minutes)}m`;
}

function qualityTone(state: string) {
  if (state === "TRADING") return "live" as const;
  if (state === "PREOPEN") return "snapshot" as const;
  return "watch" as const;
}

export default function Home() {
  const snapshot = trpc.dreamdex.snapshot.useQuery(undefined, { refetchInterval: 15_000, retry: 1 });
  const data = snapshot.data;
  const markets = data?.markets ?? [];
  const connectionState = snapshot.isError ? "ERROR" : data?.state;
  const sourceMessage = snapshot.isError ? "The verified DreamDEX query failed. Market values are withheld until the source recovers." : data?.message;
  const leadMarket = markets[0];
  const leadProbability = leadMarket?.midPercent ?? leadMarket?.lastPricePercent;

  return <SignalShell>
    <section className="relative overflow-hidden border-b border-white/[0.07] pb-12"><div className="pointer-events-none absolute right-[-14%] top-[-25%] h-[430px] w-[720px] bg-[url('/manus-storage/proofcast-command-texture_45fb6632.png')] bg-cover bg-center opacity-45 mix-blend-screen" /><div className="relative"><div className="flex flex-col justify-between gap-7 xl:flex-row xl:items-end"><div><div className="mb-4 flex items-center gap-3"><span className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#d7f36b]">Command center</span><span className="h-px w-10 bg-[#d7f36b]/40" /><span className="text-[10px] uppercase tracking-[0.18em] text-[#677285]">Accountable forecasting intelligence</span></div><h1 className="max-w-3xl font-display text-4xl font-semibold leading-[0.98] tracking-[-0.07em] text-white sm:text-6xl">See the signal.<br /><span className="text-[#7f8a9e]">Own the decision.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#8d98aa]">Live Event Contract market context, a transparent model boundary, and a place to record an inspectable forecast. No execution path is enabled.</p></div><div className="flex items-center gap-3"><div className="flex -space-x-2"><div className="h-8 w-8 rounded-full border-2 border-[#080b10] bg-[#263244]" /><div className="h-8 w-8 rounded-full border-2 border-[#080b10] bg-[#58617e]" /><div className="h-8 w-8 rounded-full border-2 border-[#080b10] bg-[#d7f36b]" /></div><div className="text-[11px] leading-4 text-[#7f8a9e]">Market → model → you<br /><span className="text-white">The proof loop begins here.</span></div></div></div><div className="mt-11 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5 shadow-2xl shadow-black/20"><Metric label="Markets monitored" value={snapshot.isLoading ? "…" : String(markets.length).padStart(2, "0")} detail={connectionState === "LIVE" ? "Verified current windows" : "No demo values substituted"} /></div><div className="rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5"><Metric label="Source state" value={connectionState ?? "…"} detail={snapshot.isError ? "Retry the verified source from the rail" : data?.network ?? "Checking DreamDEX mainnet"} tone={connectionState === "LIVE" ? "citrine" : "muted"} /></div><div className="rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5"><Metric label="Execution boundary" value="OFF" detail="Read-only source · no wallet signer" tone="muted" /></div></div></div></section>

    <section className="pt-10"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><SectionHeading eyebrow="01 / Market surface" title="Review the active windows" detail="Market metadata comes from the DreamDEX Event Contract indexer. Best bid and ask are checked against an on-chain binary pool read." /><StatusChip tone={connectionState === "LIVE" ? "live" : connectionState === "STALE" ? "watch" : "unavailable"}>{connectionState ?? "checking"}</StatusChip></div>{snapshot.isLoading ? <div className="grid gap-4 lg:grid-cols-3">{[1, 2, 3].map(item => <div key={item} className="h-[235px] animate-pulse rounded-2xl border border-white/[0.08] bg-[#10151d]" />)}</div> : markets.length ? <div className="grid gap-4 lg:grid-cols-3">{markets.map(market => { const probability = market.midPercent ?? market.lastPricePercent; return <Link key={market.marketId} href={`/market?market=${market.marketId}`} className="group relative overflow-hidden rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5 transition-all duration-200 hover:-translate-y-0.5 hover:border-white/20"><div className={`absolute inset-y-0 left-0 w-1 ${market.marketState === "TRADING" ? "bg-[#d7f36b]" : market.marketState === "PREOPEN" ? "bg-[#8ba6ff]" : "bg-[#e9b65b]"}`} /><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="font-display text-lg font-semibold text-white">{market.asset}</span><span className="text-[10px] uppercase tracking-[0.15em] text-[#778297]">Binary contract</span></div><div className="mt-3 max-w-[260px] text-sm leading-5 text-[#d0d4da]">{market.question}</div></div><StatusChip tone={qualityTone(market.marketState)}>{market.marketState}</StatusChip></div><div className="mt-7 flex items-end justify-between"><div><div className="text-[9px] uppercase tracking-[0.17em] text-[#697487]">YES midpoint</div><div className="mt-1 font-display text-3xl font-semibold tracking-[-0.06em] text-white">{probability === null ? "—" : `${probability.toFixed(1)}%`}</div></div><div className="text-right"><div className="text-[9px] uppercase tracking-[0.17em] text-[#697487]">Time remaining</div><div className="mt-1 flex items-center justify-end gap-1.5 font-mono text-sm text-[#d7f36b]"><Clock3 size={13} /> {remainingLabel(market.secondsToExpiry)}</div></div></div><div className="mt-5 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d7f36b]" style={{ width: `${probability ?? 0}%`, opacity: probability === null ? 0 : 1 }} /></div></Link>; })}</div> : <div className="rounded-2xl border border-white/[0.08] bg-[#10151d] p-7"><div className="font-display text-xl text-white">{snapshot.isError ? "Verified source query failed" : "No verified market values available"}</div><p className="mt-2 max-w-xl text-sm leading-6 text-[#8d98aa]">{sourceMessage ?? "The source is still being checked."} Proofcast does not replace an unavailable live feed with interface snapshots.</p></div>}</section>

    <section className="mt-12 grid gap-5 xl:grid-cols-[1.25fr_0.75fr]"><div className="rounded-2xl border border-white/[0.08] bg-[#10151d] p-6 sm:p-8"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#697487]">What Proofcast keeps separate</div><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-0.05em] text-white">Forecast quality is not trading performance.</h2></div><Layers3 size={18} className="text-[#8ba6ff]" /></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><GitCompareArrows size={17} className="text-[#d7f36b]" /><div className="mt-4 text-[10px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Forecast</div><p className="mt-2 text-xs leading-5 text-[#adb6c4]">Record what you believed and how confident you were.</p></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><ShieldCheck size={17} className="text-[#8ba6ff]" /><div className="mt-4 text-[10px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Decision</div><p className="mt-2 text-xs leading-5 text-[#adb6c4]">Review validated market status, spread, and book context.</p></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><Activity size={17} className="text-[#e9b65b]" /><div className="mt-4 text-[10px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Proof</div><p className="mt-2 text-xs leading-5 text-[#adb6c4]">Inspect the outcome without rewriting the original record.</p></div></div></div><div className="rounded-2xl border border-[#d7f36b]/16 bg-[#d7f36b]/[0.035] p-6 sm:p-8"><div className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#d7f36b]">Signal instrument / verified market</div><h2 className="mt-3 font-display text-2xl font-semibold tracking-[-0.05em] text-white">Compare the belief stack.</h2>{leadMarket && leadProbability !== null ? <div className="mt-6 rounded-xl border border-white/[0.07] bg-[#0a0e14]/80 p-4"><ProbabilityBand market={leadProbability} compact /></div> : <p className="mt-6 rounded-xl border border-white/[0.07] bg-[#0a0e14]/80 p-4 text-sm leading-6 text-[#8d98aa]">A probability comparison is available only after a verified market value returns.</p>}<p className="mt-4 text-sm leading-6 text-[#99a4b4]">The EventForge calculation layer has not been connected yet; it is intentionally not estimated or simulated here.</p><Link href={leadMarket ? `/market?market=${leadMarket.marketId}` : "/market"} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#d7f36b] px-4 py-3 text-[11px] font-bold uppercase tracking-[0.13em] text-[#10140d] transition-transform hover:bg-[#e2fa80] active:scale-[0.97]">Open market decision <ArrowRight size={15} /></Link></div></section>
  </SignalShell>;
}
