/* Proofcast / Signal Room: Command Center prioritizes current market context, provenance, and the next review action. */
import { Link } from "wouter";
import { Activity, ArrowRight, Clock3, GitCompareArrows, Layers3, ShieldCheck } from "lucide-react";
import { Metric, ProbabilityBand, SectionHeading, SignalShell, StatusChip } from "@/components/SignalShell";
import { marketSnapshots } from "@/lib/proofcast-data";

function QualityPill({ quality }: { quality: string }) {
  const styles = quality === "TRADEABLE" ? "bg-[#d7f36b]/10 text-[#d7f36b]" : quality === "WATCH" ? "bg-[#e9b65b]/10 text-[#e9b65b]" : "bg-white/[0.06] text-[#9ca6b6]";
  return <span className={`rounded-md px-2 py-1 text-[9px] font-bold uppercase tracking-[0.13em] ${styles}`}>{quality}</span>;
}

export default function Home() {
  return <SignalShell>
    <section className="relative overflow-hidden border-b border-white/[0.07] pb-12"><div className="pointer-events-none absolute right-[-14%] top-[-25%] h-[430px] w-[720px] bg-[url('/manus-storage/proofcast-command-texture_45fb6632.png')] bg-cover bg-center opacity-45 mix-blend-screen" /><div className="relative"><div className="flex flex-col justify-between gap-7 xl:flex-row xl:items-end"><div><div className="mb-4 flex items-center gap-3"><span className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#d7f36b]">Command center</span><span className="h-px w-10 bg-[#d7f36b]/40" /><span className="text-[10px] uppercase tracking-[0.18em] text-[#677285]">Accountable forecasting intelligence</span></div><h1 className="max-w-3xl font-display text-4xl font-semibold leading-[0.98] tracking-[-0.07em] text-white sm:text-6xl">See the signal.<br /><span className="text-[#7f8a9e]">Own the decision.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#8d98aa]">A focused briefing room for reviewing market context, comparing a transparent model reference, and creating an inspectable forecast.</p></div><div className="flex items-center gap-3"><div className="flex -space-x-2"><div className="h-8 w-8 rounded-full border-2 border-[#080b10] bg-[#263244]" /><div className="h-8 w-8 rounded-full border-2 border-[#080b10] bg-[#58617e]" /><div className="h-8 w-8 rounded-full border-2 border-[#080b10] bg-[#d7f36b]" /></div><div className="text-[11px] leading-4 text-[#7f8a9e]">Market → model → you<br /><span className="text-white">The proof loop begins here.</span></div></div></div><div className="mt-11 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5 shadow-2xl shadow-black/20"><Metric label="Markets monitored" value="03" detail="BTC + ETH snapshot set" /></div><div className="rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5"><Metric label="Quality gate" value="01" detail="Potentially tradeable in snapshot" tone="citrine" /></div><div className="rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5"><Metric label="Proof profile" value="—" detail="Wallet required for persistence" tone="muted" /></div></div></div></section>
    <section className="pt-10"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><SectionHeading eyebrow="01 / Market surface" title="Review the active windows" detail="These are clearly labeled interface snapshots while verified DreamDEX data is unavailable." /><StatusChip tone="unavailable">Live data unavailable</StatusChip></div><div className="grid gap-4 lg:grid-cols-3">{marketSnapshots.map((market, index) => <Link key={market.marketId} href={`/market?market=${index}`} className="group relative overflow-hidden rounded-2xl border border-white/[0.08] bg-[#10151d]/85 p-5 transition-all duration-200 hover:-translate-y-0.5 hover:border-white/20"><div className={`absolute inset-y-0 left-0 w-1 ${market.quality === "TRADEABLE" ? "bg-[#d7f36b]" : market.quality === "WATCH" ? "bg-[#8ba6ff]" : "bg-[#e9b65b]"}`} /><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="font-display text-lg font-semibold text-white">{market.symbol}</span><span className="text-[10px] uppercase tracking-[0.15em] text-[#778297]">{market.name}</span></div><div className="mt-3 max-w-[220px] text-sm leading-5 text-[#d0d4da]">{market.question}</div></div><QualityPill quality={market.quality} /></div><div className="mt-7 flex items-end justify-between"><div><div className="text-[9px] uppercase tracking-[0.17em] text-[#697487]">Market probability</div><div className="mt-1 font-display text-3xl font-semibold tracking-[-0.06em] text-white">{market.marketProbability}%</div></div><div className="text-right"><div className="text-[9px] uppercase tracking-[0.17em] text-[#697487]">Time remaining</div><div className="mt-1 flex items-center justify-end gap-1.5 font-mono text-sm text-[#d7f36b]"><Clock3 size={13} /> {market.timeRemaining}</div></div></div><div className="mt-5 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d7f36b]" style={{ width: `${market.marketProbability}%`, opacity: index === 0 ? 1 : 0.55 }} /></div></Link>)}</div></section>
    <section className="mt-12 grid gap-5 xl:grid-cols-[1.25fr_0.75fr]"><div className="rounded-2xl border border-white/[0.08] bg-[#10151d] p-6 sm:p-8"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#697487]">What Proofcast keeps separate</div><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-0.05em] text-white">Forecast quality is not trading performance.</h2></div><Layers3 size={18} className="text-[#8ba6ff]" /></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><GitCompareArrows size={17} className="text-[#d7f36b]" /><div className="mt-4 text-[10px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Forecast</div><p className="mt-2 text-xs leading-5 text-[#adb6c4]">Record what you believed and how confident you were.</p></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><ShieldCheck size={17} className="text-[#8ba6ff]" /><div className="mt-4 text-[10px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Decision</div><p className="mt-2 text-xs leading-5 text-[#adb6c4]">Review model context, quality, spread, and execution conditions.</p></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><Activity size={17} className="text-[#e9b65b]" /><div className="mt-4 text-[10px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Proof</div><p className="mt-2 text-xs leading-5 text-[#adb6c4]">Inspect the outcome without rewriting the original record.</p></div></div></div><div className="rounded-2xl border border-[#d7f36b]/16 bg-[#d7f36b]/[0.035] p-6 sm:p-8"><div className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#d7f36b]">Signal instrument / BTC preview</div><h2 className="mt-3 font-display text-2xl font-semibold tracking-[-0.05em] text-white">Compare the belief stack.</h2><div className="mt-6 rounded-xl border border-white/[0.07] bg-[#0a0e14]/80 p-4"><ProbabilityBand market={64} model={71} you={72} compact /></div><p className="mt-4 text-sm leading-6 text-[#99a4b4]">Market, EventForge, and your forecast are displayed together before any decision record is made.</p><Link href="/market" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#d7f36b] px-4 py-3 text-[11px] font-bold uppercase tracking-[0.13em] text-[#10140d] transition-transform hover:bg-[#e2fa80] active:scale-[0.97]">Open market decision <ArrowRight size={15} /></Link></div></section>
  </SignalShell>;
}
