/* Proof Instrument / Signal Room: live market context is treated as a primary evidence object, not a dashboard card grid. */
import { Link } from "wouter";
import { ArrowUpRight, Check, CircleDotDashed, Clock3, FileCheck2, ScanLine } from "lucide-react";
import { SignalShell, StatusChip } from "@/components/SignalShell";
import { trpc } from "@/lib/trpc";

function timeLabel(seconds: number) { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return hours ? `${hours}h ${minutes}m` : `${Math.max(0, minutes)}m`; }
function qualityTone(state: string) { return state === "TRADING" ? "live" as const : state === "PREOPEN" ? "snapshot" as const : "watch" as const; }

export default function Home() {
  const snapshot = trpc.dreamdex.snapshot.useQuery(undefined, { refetchInterval: 15_000, retry: 1 });
  const data = snapshot.data;
  const markets = data?.markets ?? [];
  const state = snapshot.isError ? "ERROR" : data?.state;
  const lead = markets[0];
  const probability = lead?.midPercent ?? lead?.lastPricePercent;
  return <SignalShell><div className="pi-workspace">
    <section className="pi-command-hero"><div><div className="pi-kicker"><span>01</span> Signal room / live context</div><h1>See the signal.<br /><em>Own the decision.</em></h1><p>Live Event Contract context is a reference point—not a verdict. Proofcast keeps what the market shows, what you believe, and what later resolves in separate evidence lanes.</p><div className="pi-head-actions"><Link href={lead ? `/market?market=${lead.marketId}` : "/market"} className="pi-action">Review a live market <ArrowUpRight size={16} /></Link><span className="pi-source-note">No signer · no order path</span></div></div><aside className="pi-hero-instrument"><div className="pi-instrument-top"><span>Source condition</span><StatusChip tone={state === "LIVE" ? "live" : state === "STALE" ? "watch" : "unavailable"}>{state ?? "checking"}</StatusChip></div><div className="pi-orbit"><i /><i /><i /></div><div className="pi-instrument-copy"><b>{state === "LIVE" ? "Verified market context" : "Market context withheld"}</b><span>{state === "LIVE" ? "DreamDEX Event Contract snapshot" : snapshot.isError ? "The verified source needs a successful retry." : "Checking DreamDEX mainnet."}</span></div><div className="pi-instrument-line"><span>Market</span><span>Model</span><span>You</span></div></aside></section>

    <section className="pi-signal-grid"><div className="pi-panel pi-market-panel"><div className="pi-panel-head"><div><div className="pi-kicker"><span>Live board</span> Verified windows</div><h2>Active market reference</h2></div><span className="pi-timestamp">{snapshot.isLoading ? "Syncing" : `${markets.length} signals`}</span></div>{snapshot.isLoading ? <div className="pi-loading-lines"><i /><i /><i /></div> : lead ? <><div className="pi-lead-market"><div><div className="pi-market-id">{lead.asset} / EVENT CONTRACT</div><h3>{lead.question}</h3><p>Market ID: {lead.marketId.slice(0, 18)}… · Indexed {lead.indexedStatus}</p></div><div className="pi-probability"><b>{probability == null ? "—" : `${probability.toFixed(1)}%`}</b><span>YES midpoint</span></div></div><div className="pi-market-rail"><span className="pi-rail-fill" style={{ width: `${probability ?? 0}%` }} /><span className="pi-rail-dot" style={{ left: `${probability ?? 0}%` }} /></div><div className="pi-market-meta"><span><b>{timeLabel(lead.secondsToExpiry)}</b> window remaining</span><span><b>{lead.spreadBps == null ? "—" : `${lead.spreadBps} bps`}</b> observed spread</span><StatusChip tone={qualityTone(lead.marketState)}>{lead.marketState}</StatusChip></div></> : <div className="pi-empty-instrument"><ScanLine size={23} /><b>Verified source is unavailable</b><span>{snapshot.isError ? "No market values are substituted while the source is unavailable." : data?.message ?? "The current query did not return a market."}</span></div>}</div>
      <aside className="pi-panel pi-loop-panel"><div className="pi-kicker"><span>Proof loop</span> Do not collapse the layers</div><div className="pi-loop-step"><span>01</span><div><b>Observe</b><p>Read the market, its book, and its window.</p></div></div><div className="pi-loop-step"><span>02</span><div><b>Commit</b><p>State a forecast and the confidence behind it.</p></div></div><div className="pi-loop-step"><span>03</span><div><b>Prove</b><p>Compare the outcome against the original record.</p></div></div><Link href="/proof" className="pi-text-link">Open proof ledger <ArrowUpRight size={15} /></Link></aside></section>

    <section className="pi-lane-section"><div className="pi-section-title"><div className="pi-kicker"><span>Decision hygiene</span> The durable boundary</div><h2>Forecast quality is not trading performance.</h2></div><div className="pi-lanes"><article><CircleDotDashed size={20} /><b>Market signal</b><p>Live, sourced context with a visible freshness state.</p></article><article><Check size={20} /><b>Forecast commitment</b><p>Your thesis and confidence stay separate from the market.</p></article><article><FileCheck2 size={20} /><b>Proof receipt</b><p>An outcome record exists only when the inputs can be verified.</p></article></div></section>
  </div></SignalShell>;
}
