/* Proofcast / Signal Room: proof records expose a decision’s original context without conflating forecast calibration and trading performance. */
import { ArrowRight, CheckCircle2, Clock3, FileCheck2, LockKeyhole, Scale, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { Metric, ProbabilityBand, SectionHeading, SignalShell, StatusChip } from "@/components/SignalShell";
import { proofRecords } from "@/lib/proofcast-data";

export default function ProofProfile() {
  return <SignalShell>
    <section className="flex flex-wrap items-end justify-between gap-5 border-b border-white/[0.07] pb-8"><SectionHeading eyebrow="03 / Proof profile" title="A decision stays inspectable." detail="Proofcast separates what you forecast, what you traded, and what happened. This is a visible demonstration record, not a claim about a connected account." /><StatusChip tone="snapshot">Demo history</StatusChip></section>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/[0.08] bg-[#10151d] p-5"><Metric label="Calibration" value="—" detail="Requires resolved personal forecasts" tone="muted" /></div><div className="rounded-2xl border border-white/[0.08] bg-[#10151d] p-5"><Metric label="Directional accuracy" value="—" detail="No connected sample" tone="muted" /></div><div className="rounded-2xl border border-white/[0.08] bg-[#10151d] p-5"><Metric label="Trading performance" value="—" detail="No connected positions" tone="muted" /></div></section>
    <section className="mt-10 grid gap-5 xl:grid-cols-[0.82fr_1.18fr]"><div className="rounded-2xl border border-[#d7f36b]/16 bg-[#d7f36b]/[0.035] p-6 sm:p-8"><div className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#d7f36b]">Decision receipt</div><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.06em] text-white">What I thought. What the market thought. What happened.</h2><p className="mt-5 text-sm leading-6 text-[#99a4b4]">A receipt captures the market snapshot, EventForge estimate, your forecast, and the final resolution. It does not quietly change when the market moves later.</p><div className="mt-6 rounded-xl border border-white/[0.07] bg-[#0a0e14]/80 p-4"><div className="mb-4 text-[9px] font-bold uppercase tracking-[0.17em] text-[#6f7b8f]">Receipt comparison / snapshot</div><ProbabilityBand market={64} model={71} you={72} compact /></div><div className="mt-6 space-y-3 border-t border-[#d7f36b]/14 pt-6 text-xs"><div className="flex items-center gap-3 text-[#cbd2dc]"><FileCheck2 size={15} className="text-[#d7f36b]" /> Forecast premise and confidence</div><div className="flex items-center gap-3 text-[#cbd2dc]"><Scale size={15} className="text-[#8ba6ff]" /> Market versus model comparison</div><div className="flex items-center gap-3 text-[#cbd2dc]"><TrendingUp size={15} className="text-[#e9b65b]" /> Separate forecast and trade outcome</div></div><Link href="/market" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#d7f36b] px-4 py-3 text-[11px] font-bold uppercase tracking-[0.13em] text-[#10140d] transition-transform hover:bg-[#e2fa80] active:scale-[0.97]">Create a decision record <ArrowRight size={15} /></Link></div>
      <div className="relative overflow-hidden rounded-2xl border border-white/[0.08] bg-[#10151d] p-6 sm:p-8"><div className="pointer-events-none absolute inset-0 bg-[url('/manus-storage/proofcast-receipt-paper_e369d619.png')] bg-cover bg-center opacity-20" /><div className="relative"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#697487]">Receipt ledger</div><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-0.05em] text-white">Inspectable decision history</h2></div><StatusChip tone="snapshot">Preview</StatusChip></div><div className="mt-6 overflow-hidden rounded-xl border border-white/[0.07]"><div className="hidden grid-cols-[1.45fr_0.7fr_0.7fr_0.72fr] gap-3 bg-white/[0.035] px-4 py-3 text-[9px] font-bold uppercase tracking-[0.14em] text-[#6f7b8f] sm:grid"><span>Market</span><span>Forecast</span><span>Model</span><span>Outcome</span></div>{proofRecords.map((record) => <div key={record.marketId} className="grid gap-3 border-t border-white/[0.07] px-4 py-4 sm:grid-cols-[1.45fr_0.7fr_0.7fr_0.72fr]"><div><div className="text-xs font-semibold text-white">{record.event}</div><div className="mt-1 text-[10px] text-[#697487]">{record.marketId} · {record.date}</div></div><div className="text-xs text-[#d7f36b]"><span className="mr-2 text-[9px] uppercase tracking-[0.12em] text-[#697487] sm:hidden">Forecast</span>{record.forecast}</div><div className="text-xs text-[#9db5ff]"><span className="mr-2 text-[9px] uppercase tracking-[0.12em] text-[#697487] sm:hidden">Model</span>{record.model}</div><div className="text-xs text-[#c7ced8]"><span className="mr-2 text-[9px] uppercase tracking-[0.12em] text-[#697487] sm:hidden">Outcome</span>{record.result}</div></div>)}</div><div className="mt-6 flex items-start gap-3 rounded-lg border border-white/[0.07] bg-[#0a0e14]/80 p-4 text-[11px] leading-5 text-[#7f8a9e]"><LockKeyhole size={14} className="mt-0.5 shrink-0 text-[#697487]" /> Connect a wallet and verified data layer to persist a personal record, source timestamps, settlement outcome, and any related transaction evidence.</div></div></div></section>
    <section className="mt-5 rounded-2xl border border-white/[0.08] bg-[#10151d] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#697487]">Calibration starts with enough resolved data</div><p className="mt-2 text-sm text-[#a4aebc]">Proofcast does not create a composite score or claim significance before there is a credible sample size.</p></div><div className="flex items-center gap-2 text-[11px] text-[#8993a4]"><Clock3 size={15} /> Resolution data pending integration</div></div></section>
  </SignalShell>;
}
