/* Proof Instrument / Proof Profile: receipt-oriented accountability surfaces never invent personal history. */
import { ArrowUpRight, Clock3, FileCheck2, LockKeyhole, Scale, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { SignalShell, StatusChip } from "@/components/SignalShell";

export default function ProofProfile() { return <SignalShell><div className="pi-workspace">
  <section className="pi-page-intro"><div><div className="pi-kicker"><span>03</span> Proof profile / receipt boundary</div><h1>A decision stays<br /><em>inspectable.</em></h1><p>Proofcast separates what you forecast, what you traded, and what happened. No personal record is inferred from the read-only market connection.</p></div><StatusChip tone="unavailable">No persisted records</StatusChip></section>
  <section className="pi-score-strip"><div><span>Calibration</span><b>—</b><i>Requires resolved saved forecasts</i></div><div><span>Directional accuracy</span><b>—</b><i>No connected forecast history</i></div><div><span>Trading performance</span><b>—</b><i>No wallet or position history</i></div></section>
  <section className="pi-receipt-layout"><article className="pi-panel pi-receipt-instrument"><div className="pi-kicker"><span>Decision receipt</span> Pending real inputs</div><h2>An accountable record needs real inputs.</h2><p>A future receipt will bind a verified market snapshot, EventForge estimate, forecast commitment, and eventual resolution—without silently rewriting any component later.</p><div className="pi-receipt-checks"><span><FileCheck2 size={16} /> Forecast premise and confidence</span><span><Scale size={16} /> Market versus model comparison</span><span><TrendingUp size={16} /> Separate forecast and trade outcome</span></div><Link href="/market" className="pi-action">Review a live market <ArrowUpRight size={15} /></Link></article><article className="pi-panel pi-ledger"><div className="pi-panel-head"><div><div className="pi-kicker"><span>Receipt ledger</span> Inspectable history</div><h2>No Decision Receipts yet</h2></div><StatusChip tone="unavailable">Empty</StatusChip></div><div className="pi-ledger-empty"><FileCheck2 size={27} /><b>There is no record to overstate.</b><p>The current DreamDEX layer supplies public market context only. Forecast persistence, settlement tracking, wallet linkage, and model snapshots require their own verified flows.</p></div><div className="pi-lock-note"><LockKeyhole size={14} /> A receipt begins only when Proofcast can persist a source timestamp, market identifier, user forecast, and settlement evidence.</div></article></section>
  <section className="pi-panel pi-calibration-note"><div><div className="pi-kicker"><span>Calibration standard</span> Evidence before score</div><h2>Significance starts with enough resolved data.</h2><p>Proofcast does not create a composite score or claim calibration before there is a credible sample.</p></div><div><Clock3 size={16} /> Resolution data pending integration</div></section>
</div></SignalShell>; }
